AWSTemplateFormatVersion: "2010-09-09"
Description: Zundoko-dotnet Infrastructure
Resources:
  ZundokoApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: zundoko
  ListResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ZundokoApi.RootResourceId
      PathPart: list
      RestApiId: !Ref ZundokoApi
    DependsOn: ZundokoApi
  ListMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ZundokoApi
      ResourceId: !Ref ListResource
      AuthorizationType: None
      HttpMethod: GET
      Integration:
        Type: MOCK
  PlayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ZundokoApi.RootResourceId
      PathPart: play
      RestApiId: !Ref ZundokoApi
    DependsOn: ZundokoApi
  PlayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ZundokoApi
      ResourceId: !Ref PlayResource
      AuthorizationType: None
      HttpMethod: POST
      Integration:
        Type: MOCK
  PlayOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ZundokoApi
      ResourceId: !Ref PlayResource
      AuthorizationType: None
      HttpMethod: OPTIONS
      Integration:
        Type: MOCK
