name: Build

on:
  push:
    paths:
      - src/**
      - .github/workflows/build.yml

jobs:
  build:
    uses: ushibutatory/actions/.github/workflows/dotnet-build.yml@main
    with:
      solution_dir: /src/ZundokoSolution
      with_nuget: true
    secrets:
      nuget_user: ${{ secrets.NUGET_USER }}
      nuget_pass: ${{ secrets.NUGET_PASS }}
